name: Thunder Test Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Start Thunder Server
        run: |
          go run server/main.go &
          # Consider using a readiness check instead of sleep if needed
          sleep 5

      - name: Run Integration Tests (gRPC + REST)
        run: go test -v ./backend/... ./db/...
