name: Thunder Test Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: "testsecret"  # Ensure this variable is set for your tests

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Dependencies
        run: go mod tidy

      - name: Generate Self-Signed Certificates
        run: |
          mkdir -p certs
          openssl req -x509 -newkey rsa:4096 -keyout certs/server.key -out certs/server.crt -days 365 -nodes \
            -subj "/CN=localhost" \
            -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Start Thunder Server
        run: |
          go run server/main.go &
          # Adjust the sleep duration or implement a readiness check if needed
          sleep 5

      - name: Run Tests (gRPC + REST)
        run: go test -v ./backend/... ./db/...
